#!/usr/bin/sh

xsetroot -cursor_name left_ptr
wmname LG3D
sxhkd &
$HOME/.config/polybar/launch.sh
#xdo above -t $(xdo id -n root) $(xdo id -n polybar)
override-redirect = true
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         3
bspc config window_gap           9.6

#bspc config normal_border_color "#D23D3D"
bspc config normal_border_color "#1e222a"
bspc config focused_border_color "#2c3038"
#bspc config focused_border_color "#24d1c5"
#bspc config presel_feedback_color "#2A303D"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^8' state=floating follow=on

bspc rule -a firefox desktop='^2' follow=on
bspc rule -a Brave-browser-beta desktop='^2' follow=on
bspc rule -a Code desktop='^3' follow=on follow=on
bspc rule -a Pcmanfm desktop='^5' follow=on follow=on
bspc rule -a Blueman-manager desktop='^8' follow=on follow=on
bspc rule -a obs desktop='^9' follow=on follow=on
bspc rule -a 'Mullvad VPN' state=floating  follow=on
bspc rule -a Dunst state=floating  follow=on
# bspc rule -a Protonvpn state=floating  follow=on
bspc rule -a Xfce4-terminal state=floating  follow=on


bspc rule -a scrcpy desktop='^6' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a jetbrains-idea-ce state=floating 


#Autostart

killall -q nm-tray 

nm-tray &
blueman-applet &
dunst &





